source 'https://bitbucket.org/flowtoolz/podspecs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'TodayList' do

    pod 'PureLayout', '3.0.2'
  
    pod 'Flowtoolz', :path=> '../../Flowtoolz-Cocoapod'

    target 'TodayListTests' do

        inherit! :search_paths


    end

end
