use_frameworks!

platform :osx, '10.12'

target 'Flowlist' do

    pod 'GetLaid', :path=> '../../GetLaid'
    pod 'UIObserver', :path=> '../../UIObserver'
    pod 'UIToolz', :path=> '../../UIToolz'
    pod 'FoundationToolz', :path=> '../../FoundationToolz'
    pod 'SwiftObserver', :path=> '../../SwiftObserver'
    pod 'SwiftyToolz', :path=> '../../SwiftyToolz'
    pod 'PromiseKit', '~> 6.7'

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['MACOSX_DEPLOYMENT_TARGET'] = '10.12'
        end
    end
end
